# nodns-server configuration
# ⚠️ SECURITY WARNING: Certificate features can be extremely dangerous

# DNS server port (requires root/admin for port 53)
port: 53

# Nostr relays to query for DNS records and certificates
relays:
  - "wss://relay.damus.io"
  - "wss://nos.lol"
  - "wss://relay.snort.social"
  - "wss://relay.nostr.band"
  - "wss://nostr.wine"

# Forward DNS servers for non-.nostr domains
forward_dns:
  - "1.1.1.1"  # Cloudflare
  - "1.0.0.1"  # Cloudflare

# Default TTL for DNS responses (seconds)
ttl: 3600

# Certificate settings - ⚠️ EXTREMELY DANGEROUS ⚠️
certificates:
  # NEVER enable auto_install in production!
  auto_install: true
  # Always prompt users before installing certificates
  prompt_user: true
  # Avoid fingerprint/Touch ID prompts (recommended for DNS servers)
  non_interactive: true
  # Only install certificates for these TLDs (empty = all TLDs)
  required_tlds: ["nostr", "net"]
  # Skip expired certificates
  skip_expired: true
  # Skip self-signed certificates
  skip_self_signed: false
  # Skip certificates older than this many days
  max_age_days: 365
  # Path to certificate audit log file
  audit_log: ""
  # RECOMMENDED: Completely disable certificate functionality
  disable_dangerous: false

# Logging configuration
logging:
  level: "info"     # debug, info, warn, error
  format: "text"    # text, json
  audit_log: ""     # Path to audit log file
